name: Hadolint
on:
  - pull_request
  - push
jobs:
  hadolint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
